### ISSUE TITLE
NPC wont open Gates / Doors

### ISSUE THREAD

**Issue by Regnak85** [Nutty101/NPC_Destinations2#14]
Dont really know, if this is a bug or not... Maybe, i doing something wrong...

Created NPC, made autoset, then give him Sunset and Sunrise Position. 

Sunrise was on a Farm, Sunset in a House.

When the sun was going down, the NPC goes out of the Farm, goes straight to the House but then, he stopped before the gate and nothing happens. After a while, the NPC goes a longer way, till he came to the House... At the House, he stands before the Door... And then, he "warped" into the house.

Is something needed to do, so they can open Gates and doors? (Ive made the Hook, on Gates and Doors, but that doesnt work)  Maybe some Worldguard Thing? Config? Anything?

**Comment by Nutty101** [comment]
There are issues, not going to lie. The problem is that the navigation in minecraft broke doors and stairs. So citizens teleports them thru doors, but at odd angle's they can get stuck. For testing, try to make a corridor to the door and see if that fixes it. If so, then this is the exact issue I have been looking at working around, but have yet to figure out how to resolve it fully.

**Comment by Nutty101** [comment]
Rebuilt in the new version. Changed how i manage this. New headaches, but some what solves this.
