### ISSUE TITLE
[Question] How to make a npc go to each location, one after one

### ISSUE THREAD

**Issue by Tiplish** [Nutty101/NPC_Destinations2#23]
Hi,

The Idea is to have a guard who patrol and when a player interract with him, he stopped. When a player left conversation (From Betonquest), the guard continue his path. The specific thing is that, at night, he just go back to his home and stop speaking.

To do this, i would make a list of destination and when it's the night, he finish his path and go back home.

I think that the biggest part who block me is the /npcdest locaddcmd combined with goloc command. There is not many information on the wiki :s 

Thanks !

**Comment by Nutty101** [comment]
Does the path need to be in a set order for the patrol? or would a set group of locations to move around between work? 

So if I am understanding you on this one (Snagged some town image off google, but I think it will work for this)
During the night, you want the NPC to stay at point A.

During the day you would like the NPC to move between locations B,C,D,E,F.  Pausing to for players that are close to you.

![image](https://user-images.githubusercontent.com/14265073/46327327-af4c2680-c5c6-11e8-91f7-f4f4417e6f1c.png)

**Comment by Tiplish** [comment]
The path need to be set of order, i don't use random location for the moment (it looks more complicated and i prefer to go step by step :p)

Exactly o/ and vice versa (patrolling the night with a torch (i see that i can do it with an add-on) and stay at a point during the day.

**Comment by bundabrg** [comment]
I'll just add since this relates to https://github.com/Co0sh/BetonQuest/issues/851

You can also use npcdest's BQ additions. Very quick docs:

## event: `npcdest_goloc {npcId} {loc#} {duration to stay}
loc# can be either the number or UUID

Send NPC to the location for duration seconds

I don't think the code supports unlimited duration at the moment (Actually @Nutty101 you have a condition in there that's impossible to reach and I wonder if its supposed to be if duration is left out?)

## condition: `npcdest_currentlocation {npcId} {loc#}
loc# can be either the number or UUID

Returns true if npc is at location

## condition: `npcdest_distancetolocation {npcId} {loc#} {distance}
loc# can be either the number or UUID

Returns true if the npc is distance or less from location

**Comment by Tiplish** [comment]
So for that, i will need that betonquest detect time of day too :(
